### ISSUE TITLE
No Cortex Registers view and Disassembly View 

### ISSUE THREAD

**Issue by MucaGinger** [MaJerle/stm32-cube-cmake-vscode#21]
I just finished your tutorial and most of the stuff works as should. Only disassembly view and cortex registers view (in my case probably cortex live watch) aren't "operational" yet.

When searching for disassembly view from command palette, I get this:

![no_disassembly_cortex-debug](https://github.com/MaJerle/stm32-cube-cmake-vscode/assets/79907158/893a244e-7b40-4c41-83fc-885320942a0e)

However I managed to find some other form of memory view (probably default vscode memory view?) but it doesn't look like it is the one `cortex-debug` extension is providing. This is what I get:

![default_disassembly](https://github.com/MaJerle/stm32-cube-cmake-vscode/assets/79907158/51dcd20d-21ad-4be3-bbe8-92d89210e31c)

And for cortex register view I subsequently enabled `liveWatch` property in `launch.json` file as the hint says, however no changes to current progress after restarting debug session. As far as I know I should be able to see core registers in that section? Well, this is what I get and my `launch.json` file:

![no_cortex_registers_view](https://github.com/MaJerle/stm32-cube-cmake-vscode/assets/79907158/dfa4c8e5-dd6a-4551-b67b-cb5458d7cfbd)

**Comment by MucaGinger** [comment]
It seems Cortex Registers View was moved to Variable View as one of the available drop-down lists. And for Disassembly view, it seems I cannot open it like you could normally do (or right-clicking code and opening Disassembly View from there - both aren't available for me). I find the other Disassembly view from your tutorial a bit more "aesthetic looking", however I can probably get along the existing one as well.

**Comment by MaJerle** [comment]
- Disassembly view provides nice view of the C code and assembly next to that -> view that you have shown
- Cortex-Live-watch is a generic variable live watch. It has nothing to do with cortex registers. You have to add variable

All looks ok.
