### ISSUE TITLE
What license is this project under?

### ISSUE THREAD

**Issue by benmcmorran** [MaJerle/stm32-cube-cmake-vscode#6]
I'm interested incorporating the `converter.py` script into a larger project, but there doesn't appear to be any checked-in license information in this repo. Can you add a license (preferably a permissive OSS license) to clarify what kinds of reuse are allowed?

**Comment by MaJerle** [comment]
Done https://github.com/MaJerle/stm32-cube-cmake-vscode/blob/main/LICENSE

**Comment by benmcmorran** [comment]
Thanks!
